plone/training

- plone_training_config/instructions.rst
- plone_training_config/what_vagrant_does.rst
The URL https://github.com/plone/training/raw/plone5/plone_training_config.zip returns a 302 response to https://raw.githubusercontent.com/plone/training/plone5/plone_training_config.zip.  If one uses curl instead of wget, it's better to have the latter.
> Use non-redirected link for plone_training_config.zip.

- addons.rst
- timing.rst
This fixes some ore typos and some little mistake I made
> Fix add on

- addons.rst
- api.rst
- embed.rst
- events.rst
- extending.rst
- thirdparty_behaviors.rst
- timing.rst
- viewlets_1.rst
- views_3.rst
- zpt.rst
> Some typo fixes

- addons.rst
This fixes a tiny bug in rst in the 5 branch
> Fix rst in Plone 5 branch

- addons.rst
- views_3.rst
This fixes a tiny bug in the rst syntax of this document
> Sven fix rst 4

- features.rst
- plone5.rst
Plus, I deleted a reference to a "banner", which is either new to me, or something that no longer exists.
> Small fixes to unit 6 and 7.

- about.rst
Fixing typos and rst errors while doing a review.
> Review and small fixes

- .travis.yml
- Add config setting for ssl key checking
> Add config for StrictHostKeyChecking

- zpt_2.rst
https://github.com/plone/mockup/issues/464#issuecomment-74671684 was closed and fixed.
> remove note related to the moment pattern

- theming/adv-resource-registry.rst
Minor text adjustments and Adding information on site-id parameter from plone-compile-resources script
> Minor edits

- testing.rst
People did not find this documentation
> Link to plone.app.testing documentation

- theming/theme-package.rst
As finally discussed with Simone...
> fix unprecise insert instruction for html snippet

- CHANGES.txt
- theming/theme-package.rst
> Fix directions which led to duplicate resourcess being delivered

- mastering_plone/add-ons.rst
- mastering_plone/configuring_customizing.rst
- mastering_plone/extending.rst
- mastering_plone/features.rst
- mastering_plone/plone5.rst
- plone_training_config/instructions.rst
... I have found during reading.
> some typos

- rapido.rst
A  couple of questions:
- where is Site Setup / Actions (I went into the ZMI to portal_actions)
- The search does not work for me.  If I put `context.app.records()` instead of `search` in the loop, the page displays my records, and the totals are `> 0`.  So I don't know why search does not return anything.
> Fix a couple of bugs in the top5 blocks.

- CHANGES.txt
- mastering_plone/behaviors_2.rst
- mastering_plone/dexterity_2.rst
- mastering_plone/reusable.rst
Suggestions for exercises for the behaviors_2 chapter.
> Exercises for behaviors_2/fix some emphasis

- CHANGES.txt
- mastering_plone/configuring_customizing.rst
- mastering_plone/dexterity.rst
- mastering_plone/user_generated_content.rst
- theming/ttw-advanced.rst
- theming/ttw-advanced_2.rst
- ttw/mosaic.rst
Apply menuselection to menu navigation, 
misc markup: file, guilabel, literals, 
fix a typo ..
> Markup guilabel etc

- CHANGES.txt
- theming/ttw-advanced.rst
- theming/ttw-advanced_2.rst
- visitor-only, logged-in, Diazo-based; see
https://en.wikipedia.org/wiki/Compound_modifier
- punctuate bullet list items.
- markup literals properly, also when used as definition list terms.
- it's XPath, not Xpath.
> Editing while reading new TTW-advanced-2 edits

- CHANGES.txt
- solr-training/a-fancy-custom-search-page.rst
- solr-training/first-steps.rst
- solr-training/how-does-collective-solr-work.rst
- solr-training/production-setup.rst
- solr-training/setup.rst
- solr-training/solr-alternatives.rst
- solr-training/solr-configuration.rst
- solr-training/solr-gui.rst
- solr-training/solr-testing.rst
Mostly just rst syntax and some typos here and there
> Solr docs review

- CHANGES.txt
- README.rst
> Update README.rst to refer to how to build the docs locally.

- CHANGES.txt
- README.rst
- conf.py
- mastering_plone/buildout_1.rst
- mastering_plone/restapi.rst
- theming/ttw-advanced_2.rst
These are only a few of the warnings I was able to fix. There are dozens more, but I couldn't figure out how to get them to pass.
> Fix miscellaneous Sphinx warnings on clean build

- CHANGES.txt
- mastering_plone/api.rst
- mastering_plone/zpt_2.rst
the fact that it is included in Plone though not used by Plone itself. https://github.com/plone/training/issues/234
> update explanation of API

- theming/theme-package.rst
I, Gian-Maria Daffré, agree to have this published under Creative Commons 4.0 International BY
> changed loot to lot

- CHANGES.txt
- mastering_plone/buildout_1.rst
- mastering_plone/eggs1.rst
- mastering_plone/intro.rst
- mastering_plone/roadmap.rst
- Fix various typos
- Improve wording
> Improve wording

- theming/theme-package.rst
Instead, use a virtualenv for buildout.
Possible fix for #260.
> Do not run pip as root

- CHANGES.rst
- mastering-plone/installation.rst
> Updated link

- angular/angular.rst
I can split this into separate chapters tomorrow.
After I fixed the previous rst issues, these new ones cropped up.  I have no idea what they mean, since the output is highlighted just fine.
```
angular/angular.rst:315: WARNING: Could not lex literal_block as "html". Highlighting skipped.
angular/angular.rst:338: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
angular/angular.rst:455: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
angular/angular.rst:743: WARNING: Could not lex literal_block as "html+ng2". Highlighting skipped.
angular/angular.rst:800: WARNING: Could not lex literal_block as "html+ng2". Highlighting skipped.
angular/angular.rst:820: WARNING: Could not lex literal_block as "css". Highlighting skipped.
angular/angular.rst:1016: …
```
> Fix some rst issues

- CHANGES.rst
- angular/angular.rst
- angular/index.rst
- mastering-plone/restapi.rst
- solr/a-fancy-custom-search-page.rst
- theming/ttw-advanced-2.rst
- ttw/basic.rst
- ttw/configuring-customizing.rst
- ttw/index.rst
- ttw/mosaic.rst
- ttw/rapido.rst
- ttw/ttw-advanced-2.rst
- ttw/ttw-advanced.rst
Also restore the content of `ttw-advanced-2` as recommended https://github.com/plone/training/pull/289#discussion_r143350922
> Fix formatting typos etc

- CHANGES.rst
- ttw/ttw-advanced-2.rst
These are edits from the theming training. They look like improvements to me, not sure if heading styles need to be changed.
> Restore edits that got stepped on

- angular/advanced.rst
- angular/aggregating.rst
- angular/angular.rst
- angular/authentication.rst
- angular/configuration.rst
- angular/deploying.rst
- angular/footer.rst
- angular/index.rst
- angular/installing.rst
- angular/overriding.rst
- angular/sdk.rst
- angular/summary.rst
- angular/theming.rst
- angular/using.rst
- angular/views.rst
- angular/whatisangular.rst
@ebrehault I broke the training up into shorter chapters.  What do you think?
> Split angular training into shorter chapters.

- mastering-plone/registry.rst
- fix vocabulary (needs implementer instead of provider)
- add example to translate titles
- fix indents
> fix and improve section on vocabularies

- CHANGES.rst
- theming/basic.rst
- ttw/basic.rst
in the ttw and theming training first chapter.
> Explanation about less variables and development/production mode

- gatsby/data.rst
- gatsby/howitworks.rst
- gatsby/installing.rst
- gatsby/pages.rst
- gatsby/whatisgatsby.rst
@cekk A couple adjustments I made here. Do let me know about your opinions through comments, I could change accordingly.
> Minor fixes and review

- transmogrifier/about/glossary.rst
- transmogrifier/blueprints.rst
- transmogrifier/export.rst
- transmogrifier/import.rst
- transmogrifier/pipeline.rst
- transmogrifier/users-migration.rst
Adding fixes for issues found during the training
> Transmogrifier

- react/actions.rst
- react/callbacks.rst
- react/component.rst
- react/event_handlers.rst
- react/external_data.rst
- react/forms.rst
- react/initial_form_data.rst
- react/lifecycle_methods.rst
- react/links.rst
- react/redirects.rst
- react/reducer_tests.rst
- react/redux.rst
- react/reusable_component.rst
- react/routes.rst
- react/snapshot_testing.rst
- react/state.rst
- react/styling.rst
Currently work in Progress
Highlight Changes and add information to training materials
> Improvement of React Trainings, by highlighting changes

- mastering-plone/installation.rst
Per https://community.plone.org/t/plone-5-2a2-released/7734/18?u=stevepiercy
> Update the versions of Plone and macOS for installation

- javascript/about/glossary.rst
- javascript/conf.py
- javascript/development-process.rst
- javascript/exercises/1.rst
- javascript/exercises/10.rst
- javascript/exercises/11.rst
- javascript/exercises/12.rst
- javascript/exercises/13.rst
- javascript/exercises/2.rst
- javascript/exercises/3.rst
- javascript/exercises/4.rst
- javascript/exercises/5.rst
- javascript/exercises/6.rst
- javascript/exercises/7.rst
- javascript/exercises/8.rst
- javascript/exercises/9.rst
- javascript/exercises/index.rst
- javascript/index.rst
- javascript/javascript-scratchpad.rst
- javascript/mockup.rst
- javascript/requirejs-modules.rst
- javascript/training-installation.rst
- react/bootstrap.rst
Setup instructions updated according to https://github.com/collective/collective.jstraining/pull/3
Fixed some typos and added other minor updates to the training and the exercises. No major changes except to the setup instructions.
> JS Training update

- mastering-plone/restapi.rst
s. https://github.com/collective/ploneconf.site/pull/4
> use Vue.js in RestAPI chapter

- .gitignore
- volto/override-components.rst
Having the final location of the logo was much more clear for me.
> Additional explanation of the custom Logo.svg location.

- deploy.sh
Update deploy script to handle errors during rsync and properly fail the build
> Improve deploy.sh

- react/actions.rst
Fixes issue #432.
I hope I did the line numbers correctly. I have not tried building the documentation locally. But I think I counted correctly.
> React: fixed code and highlighting in 14.2.

- wsgi/bjoern.rst
- wsgi/gunicorn.rst
> Gunicorn chapter: more on workers

- voltohandson/blocksmainslider.rst
- voltohandson/breadcrumbs.rst
- voltohandson/footer.rst
- voltohandson/header.rst
- voltohandson/index.rst
- voltohandson/intro.rst
- voltohandson/introtoblocks.rst
- voltohandson/quickstart.rst
- voltohandson/requirements.rst
- voltohandson/starttheming.rst
> voltohandson wording tweaks

- voltohandson/header.rst
Docs Style Guide, grammar, and reST spacing fixes
> Volto Hands-on Updates for Header.rst

- voltohandson/quickstart.rst
- Add sections to introduce terminal sessions earlier
- Docs style guide fixes
- Grammar fixes
- Use correct reference to this training
See also #450 as it may conflict.
> Volto Hands-on Updates for Quickstart

- voltohandson/intro.rst
- Docs style guide fixes
- Grammar fixes
- Use correct reference to this training
> Volto Hands-on Intro updates

- voltohandson/header.rst
- voltohandson/quickstart.rst
- voltohandson/starttheming.rst
some small fixes I fo9und while working through the training.
> Volto handson fixes

- voltohandson/quickstart.rst
and specify the required node version 10.15.1
> clarify need to install Volto dependencies

- solr/how-does-collective-solr-work.rst
- solr/setup.rst
- solr/solr-configuration.rst
- solr/solr-gui.rst
The part in the setup where I download half a dozen files with curl is not particularly pretty, but I can't think of a much nicer way short of cloning the whole repository (which seems like overkill). Suggestions welcome, but it at least it works now.
There are some outdated bits left. I hope to find some time to update them soonish.
Refs #475
> Update Solr training

- voltohandson/quickstart.rst
...in another terminal or shell
> clarify that Plone must be running

- docs/contributing/authors.md
See https://github.com/plone/training/issues/506#issuecomment-923141581
> Expand sentence to request a Reviewer for a PR

- docs/voltohandson/requirements.md
Minor spacing issue before the google drive link.
> Minor Formatting

- docs/mastering-plone/volto_talkview.md
Removed extras  'is is a common practice ..'
> Minor Typo in 'is is'

- docs/mastering-plone/installation.md
- docs/plone_training_config/instructions.md
NodeJS LTS is not supported by a current Volto that's bootstrapped with Volto generator.
> [MPD] Update setup instructions (frontend).

- docs/mastering-plone/installation.md
> removed old Heroku mention, replaced with link to Plone.org/download

- docs/mastering-plone-5/installation.md
replaced with link to Plone.org/download
fixes #287 and #254
> removed old Heroku mention and old blog post

- docs/mastering-plone-5/dexterity_2.md
- docs/plone_training_config/instructions.md
- docs/plone_training_config/instructions_plone5.md
- docs/solr/how-does-collective-solr-work.md
- docs/solr/production-setup.md
- docs/theming/theme_diazo.md
https://github.com/plone/training/pull/505
> small fixes from my old PR 505

- docs/contributing/authors.md
> Add an admonition about adding links to training documentation

- docs/_static/custom.css
> Add guilabel and menuselection styles

- docs/conf.py
- docs/robots.txt
> Add robots.txt and configuration

- docs/react/reusable_component.md
> Removed static keyword from propTypes

- docs/contributing/index.md
- docs/contributing/setup-build.md
- Add missing html_tags and values
- Point to correct Community Forum category
- One sentence per line
- English grammar fixes
- Add link to referred document
- Clarify intent for PRs and Netlify previews
- Add seealso admonition to help install Enchant
> Follow up to https://github.com/plone/training/pull/599

- docs/conf.py
- docs/mastering-plone-5/anatomy.md
- docs/mastering-plone-5/eggs1.md
- docs/mastering-plone/anatomy.md
- docs/mastering-plone/eggs1.md
- docs/mastering-plone/volto_frontpage.md
- docs/transmogrifier/export.md
- docs/wsgi/pep-3333.md
Do not merge until PR https://github.com/plone/volto/pull/3164 is merged. It has a new label that is referenced via Intersphinx.
> Tweak linkcheck and fix broken links

- docs/conf.py
> Change html_baseurl, add sitemap_url_scheme, to generate valid URLs in sitemap

- docs/angular/footer.md
- docs/conf.py
- docs/mastering-plone-5/behaviors_1.md
- docs/mastering-plone-5/dexterity_2.md
- docs/mastering-plone-5/dexterity_reference.md
- docs/mastering-plone-5/plone5.md
- docs/mastering-plone-5/zpt_2.md
- docs/mastering-plone/behaviors_1.md
- docs/mastering-plone/dexterity_2_talk.md
- docs/mastering-plone/dexterity_reference.md
- docs/mastering-plone/upgrade_steps.md
- docs/mastering-plone/zpt_2.md
- docs/solr/production-setup.md
- docs/solr/setup.md
- docs/testing/testing_robot.md
> Port linkcheck settings

- docs/mastering-plone/installation.md
- docs/plone_training_config/instructions.md
MPD has two chapters with frontend installation instructions.
This PR reduces redundancy and therefore maintenance by
- refering in first chapter to Plone 6 docs.
- refering in second chapter to first chapter.
> MPD. Update frontend installation instructions. Reduce redundancy.

- docs/_static/patch_scrollToActive.js
- docs/conf.py
See issue https://github.com/plone/documentation/issues/1257
> Add patch scrollToActive (active main navigation item)

- docs/effective-volto/architecture/bootstrap-volto.md
- docs/effective-volto/backend/writing-block-transforms.md
- docs/effective-volto/getting-started/project.md
- docs/effective-volto/index.md
Please verify that Yeoman is in fact required.
> Effective volto fixes

- docs/_templates/layout.html
- docs/_templates/page.html
- docs/_templates/search.html
- docs/conf.py
- Add Matomo stats
- Add Hide empty submenu JavaScript from Documentation
- Remove Google Analytics
See https://github.com/plone/plone.restapi/issues/1447
> Add Matomo stats

- docs/conf.py
- docs/plone-deployment/deploy.md
- docs/plone-deployment/edit-project.md
- docs/plone-deployment/provision.md
Fixes #689 and #692 (eventually, as I am awaiting confirmation of how to create a GitHub App).
> Plone deployment clean up

- docs/_static/custom.css
- docs/_static/search_shortcut.js
- docs/_static/searchtools.js
- docs/_templates/search-field.html
- docs/_templates/search.html
- docs/conf.py
- docs/index.md
- docs/mastering-plone/configuring_customizing.md
> Improve search form. Add short cut cmd-k for focussing search field.

- docs/volto/override-components.md
Fixed the relative path as it was not correct
> Fixed the relative path

- docs/volto/bootstrap.md
Added the Note:
**Note:** Do not start your project name with `volto`, as it will cause `plone/generator-volto` to fail
Fixes #716
Solved temporarily, Need to find a correct solution for this
> Added the note because of the error

- docs/volto/bootstrap.md
Updated folder structure in the 3.3 volto docs  Closes #712
> Updated folder structure in the 3.3 volto docs

- docs/volto/bootstrap.md
> [training 'Volto'] Update instructions for setting up a simple backend

- docs/react/bootstrap.md
I have created an issue on the Latest folder_structure regarding the issue https://github.com/plone/training/issues/727 and also have added using the tree command.
I created a new branch as i was getting conflict errors , Looking forward for a review for the same.
@stevepiercy , what if we could add a note saying and telling about them about there are many files and folders inside the node-modules folder?
> updated the react folder_structure

- docs/mastering-plone/relations.md
Fixed the dropdown Typo and removed the unnecessary and.
> Fixed the issue #743

- docs/mastering-plone/behaviors_2.md
> Fixed the typo therfore #745

- docs/mastering-plone/volto_actions.md
Changed endpint to endpoint, definitly to definitely, successfull to successful
> Fixed the issue #747

- docs/voltohandson/quickstart.md
> fix typo in voltohandson/quickstart.md

- docs/_static/custom.css
Far from ideal. But fixing the badest UI I introduced recently.
> Fix title in sticky header on mobile

- docs/plone-deployment/project-edit.md
- docs/plone-deployment/project-start.md
- docs/plone-deployment/setup.md
- some minor fix to ease following the training istructions (IMHO)
- added a troubleshooting paragraph with sone other reported issues
> Plone deployment training minor fix proposal

- docs/mastering-plone/relations.md
> documentation bug for #818 regarding basePath

- docs/mastering-plone-5/behaviors_1.md
- docs/mastering-plone-5/dexterity_reference.md
- docs/mastering-plone/about_mastering.md
- docs/mastering-plone/features.md
Changes in doucmentation to fix issue #825
> FIX For Typos

- docs/_templates/components/search-field.html
fix https://github.com/plone/training/issues/845
[search training](https://training.plone.org/search.html?q=block&training=all#)
> Update search options according to available trainings

- README.md
- docs/conf.py
- docs/index.md
> Prepare for PloneConf 2024

- docs/contributing/setup-build.md
----
📚 Documentation preview 📚: https://plone6--858.org.readthedocs.build/
> Add vale usage docs

- styles/config/vocabularies/Plone/reject.txt
See #610
----
📚 Documentation preview 📚: https://plone6--859.org.readthedocs.build/
> Reject "styleguide"

- docs/mastering-plone/add-ons.md
- docs/mastering-plone/case.md
- docs/mastering-plone/events.md
- docs/mastering-plone/installation.md
- docs/mastering-plone/volto_testing.md
- docs/mastering-plone/voting-story/index.md
----
📚 Documentation preview 📚: https://plone6--862.org.readthedocs.build/
> Developing and testing a shoe couple of frontend addon and backend addon (pip, no docker)

- docs/conf.py
- requirements.txt
----
📚 Documentation preview 📚: https://plone6--863.org.readthedocs.build/
> Start using Plone Sphinx Theme

- Makefile
See #864
----
📚 Documentation preview 📚: https://plone6--865.org.readthedocs.build/
> Don't recreate the virtual environment, just delete it

- .github/workflows/rtd-pr-preview.yml
- .readthedocs.yaml
----
📚 Documentation preview 📚: https://plone6--874.org.readthedocs.build/
> Fix rtd build 2

- .github/workflows/rtd-pr-preview.yml
- docs/effective-volto/architecture/CORS.md
----
📚 Documentation preview 📚: https://plonetraining--876.org.readthedocs.build/
> We r bad spelrz

- requirements.txt
Closes #868
----
📚 Documentation preview 📚: https://plone-training--879.org.readthedocs.build/
> Remove lesscpy from requirements.txt

- docs/customizing-volto-light-theme/installing-vlt.md
Closes #885.
----
📚 Documentation preview 📚: https://plone-training--887.org.readthedocs.build/
> Replace diff with js syntax and emphasize-lines

- .vscode/settings.json
----
📚 Documentation preview 📚: https://plone-training--890.org.readthedocs.build/
> Add VSCode settings to avoid rewriting of .md files

- docs/conf.py
- docs/effective-volto/deployment/seamlessmode.md
See #536
----
📚 Documentation preview 📚: https://plone-training--893.org.readthedocs.build/
> Update excluded files.

- docs/mastering-plone/features.md
----
📚 Documentation preview 📚: https://plone-training--895.org.readthedocs.build/
> ### Placeful workflows: referencing workflow training

- docs/mastering-plone/what_is_plone.md
fixes: #897
I, Pulkit, agree to have this contribution published under Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.
----
📚 Documentation preview 📚: https://plone-training--898.org.readthedocs.build/
> Update youtube embed url for Volto training

- docs/content-editing/add-a-grid-block.md
----
📚 Documentation preview 📚: https://plone-training--904.org.readthedocs.build/
> :art: add missing kbd label

- docs/mastering-plone/features.md
Thanks @Vivek-04022001 . Integrating your feedback (https://github.com/plone/training/pull/833) in training documentation.
----
📚 Documentation preview 📚: https://plone-training--910.org.readthedocs.build/
> MPD: enhance wording (listing block)

- docs/plone-deployment/troubleshoot.md
see: https://community.plone.org/t/corepack-problems-specially-in-ci/20597
----
📚 Documentation preview 📚: https://plone-training--924.org.readthedocs.build/
> Update troubleshoot.md | add hints for missing stack-create-site step

- docs/glossary.md
----
📚 Documentation preview 📚: https://plone-training--941.org.readthedocs.build/
> Remove unused glossary term `grunt`

- .github/workflows/build_deploy.yml
----
📚 Documentation preview 📚: https://plone-training--943.org.readthedocs.build/
> Use 2024 in `build_deploy.yml`.

- requirements.txt
See https://github.com/plone/Products.CMFPlone/issues/4097
----
📚 Documentation preview 📚: https://plone-training--946.org.readthedocs.build/
> Pin plone-sphinx-theme to prepare for PLIP 4097

- docs/content-editing/index.md
The title needs a clarification and we need a second topic pointing to the latest available training / docs fort Plone 6 Classic / similar to Plone 5
----
📚 Documentation preview 📚: https://plone-training--928.org.readthedocs.build/
> Update index.md | Add an explicit Volto scope
