plone/training

- addons.rst
- api.rst
- embed.rst
- events.rst
- extending.rst
- thirdparty_behaviors.rst
- timing.rst
- viewlets_1.rst
- views_3.rst
- zpt.rst
- fix various typos
- unify words [sometimes there was a word mix]
- use same words as we use on docs.plone.org [add-on] for example
> Sven typo fix and wording 

- eggs1.rst
A python *module* is a single .py file, while a folder with a `__init__.py` file in it is a *package*:
https://docs.python.org/3/glossary.html#term-regular-package
> Small fixes to Unit 14.

- about.rst
- update install instructions, now submodule stuff is working
- remove mention of Plone 5 branch, since this branch is now master
- add instructions on how to open docs on Linux/Ubuntu from command-line, not everyone is using OS X and 'open' will not work on Linux, out of the box
> Update install instructions

- .gitignore
- Makefile
- conf.py
- plone_training_config/instructions.rst
- move logs for spell-check and link-check out of build dir
- add log dir to .gitignore
- fix broken link - again - :), there is no Plone 5 branch anymore
> Separate logs, fix link

- conf.py
- This improves conf.py in preparation of ci-testing, also it reduces sphinx build warnings/errors, the README is not part of the docs
> Improve conf.py in prep. for ci-testing

- dexterity.rst
The schema for Talks made reference to zope.schema.email.Email, this should be plone.schema.email.Email.
The term Document is not used in the interface anymore, we call them Pages. I've fixed the reference to documents in Exercise 1.
> used name Page instead of Document; fixed error in talk schema

- CHANGES.txt
- plone_training_config/instructions.rst
Had to enable virtualization in my BIOS before vagrant could be brought 'up.'  Added note to instructions.rst for specific case of ssh_exchange_identification resetting.
> Update vagrant instructions.rst to include BIOS virtualization note.

- mastering_plone/buildout_1.rst
the default name for version pinning is simply versions
> Newer versions of buildout have versions simplified

- mastering_plone/zpt.rst
The snippet of code does not hide the side bar (as in plone 4).
Rather, it hides all the elements inside the side bar.
>  Update formulation for plone 5

- CHANGES.txt
- mastering_plone/about_mastering.rst
- mastering_plone/behaviors_2.rst
- mastering_plone/eggs1.rst
- mastering_plone/reusable.rst
- mastering_plone/theming.rst
- mastering_plone/zpt_2.rst
- mosaic.rst
- plone_training_config/instructions.rst
- theming/adv-diazo.rst
- theming/creating-customizing-templates.rst
- theming/theme-package.rst
We sometimes lose syntax highlighting because pygments fails to parse the block. 
Sometimes this is quite right, but sometimes it is overly strict. 
This is especially noticeable for CFG files, where line breaks and comments confuse pygments. 
I fixed some but these remain:
```
.../training/mastering_plone/buildout_1.rst:92: WARNING: Could not lex literal_block as "ini". Highlighting skipped.
.../training/mastering_plone/buildout_1.rst:233: WARNING: Could not lex literal_block as "cfg". Highlighting skipped.
.../training/mastering_plone/buildout_1.rst:269: WARNING: Could not lex literal_block as "cfg". Highlighting skipped.
.../training/mastering_plone/eggs1.rst:133: WARNING: Could not lex literal_block as "cfg". Highlighting skipped.
.../training/mastering_plone/sneak.rst:45: WARNING: …
```
> Pygments lexer strictness

- ttw/index.rst
This adjust the naming, of the files in the index.rst of ttw.
Note: there is nothing changed in the files which are included, its is just a toctree setting.
Before:
After:
The user is already in the chapter 'ttw' we do not have to tell that in every header on the left :)
It also looks smoother on the eye :)
> Refactor: Naming of files in index

- plone_training_config/instructions.rst
When I tried to create virtualenv with this command it doesn't work. The later one `virtualenv --python=python2.7 py27` worked for me.
> Update virtualenv create command in instrauctions as there are cases where it doesn't work

- CHANGES.txt
- mastering_plone/about_mastering.rst
- plone_training_config/instructions.rst
Specify Python version for virtualenv using option, not command alias,
as alias is not always present.
See https://community.plone.org/t/typo-in-online-plone-4-training-plone-org/2914
> Specify Python version for virtualenv using option

- CHANGES.txt
- mastering_plone/features.rst
Dexterity is now supported for Working Copy Support and Placeful Workflow.
> Remove notes on features.rst that are no longer valid.

- CHANGES.txt
- _locales/anatomy.pot
- _locales/es/LC_MESSAGES/anatomy.po
- mastering_plone/anatomy.rst
In #266 links to ZCA were updated, but since then I realized two things.
1. The canonical URL for docs is https://zopecomponent.readthedocs.io/en/latest/ per https://github.com/zopefoundation/zope.component/pull/25
2. Under the section about Pyramid, the context was for how Pyramid uses ZCA, not for ZCA itself, and should in fact point to Pyramid docs at https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/zca.html
This PR corrects the URLs and makes them consistent across the translation files as well.
> Use correct links for ZCA itself and usage in Pyramid

- CHANGES.txt
- mastering_plone/features.rst
After removing the note that mentioned Working Copy Support does not work with content types created via Dexterity, there was some discussion that brought to light the known limitations by name.  This updated note does claim support but also refers directly to the known limitations, providing better information for the reader to choose how best to use the feature.
> Add note on known limitations concerning Dexterity / Working Copy Support.

- CHANGES.rst
- deployment/index.rst
- javascript/index.rst
- solr/index.rst
- theming/index.rst
- ttw/configuring-customizing.rst
- ttw/dexterity.rst
- ttw/index.rst
- ttw/ttw-advanced-2.rst
- ttw/ttw-advanced.rst
- workflow/index.rst
Uniquify IDs that are computed from toctree caption.
Inconsistent indentation caused some spaces to be included in filenames.
> Git rid of "duplicate label" warnings; add some markup

- mastering-plone/restapi.rst
In the example the body of the POST won't work in postman as cut-and-pasted because it's not valid JSON.   The reply is
{
"message": "'No JSON object could be decoded'",
"type": "DeserializationError"
}
> fix restapi example - valid JSON in POST Body

- _static/custom.css
This commit improves contrast of highlighted code via `emphasize-lines`.
It overrides the default values provided by the `pygments` style. The default styles are difficult to perceive when using a projector, as we experience during the training provided by @pbauer in Tokyo.
Specifically these styles have very little contrast between the background of the code sample and the highlighted lines:
```css
.highlight {
background: #efc;
}
```
and
```css
.highlight .hll {
background-color: #ff9;
}
```
> Improves contrast of highlighted code via `emphasize-lines`

- CHANGES.rst
- _locales/addons.pot
- _locales/es/LC_MESSAGES/addons.po
- mastering-plone/add-ons.rst
- mastering-plone/behaviors_1.rst
- mastering-plone/behaviors_2.rst
- mastering-plone/buildout_1.rst
- mastering-plone/dexterity_2.rst
- mastering-plone/dexterity_3.rst
- mastering-plone/embed.rst
- mastering-plone/events.rst
- mastering-plone/export_code.rst
- Minor fixes, like using implementer and provider decorators
- Use behavior shortnames as best practice.
- Refine misleading explanation of IFormFieldProvider
> Use behavior shortnames and fixes within the behavior explanation/ usage

- deployment/customization.rst
- deployment/letsencrypt-certbot.rst
See also:
- https://github.com/plone/ansible-playbook/issues/61
- https://github.com/plone/ansible-playbook/pull/125
> Add example of using certbot and Let's Encrypt for Deployment via Ansible

- voltohandson/blocksedit.rst
- voltohandson/contenttypesviews.rst
I did the trainiing with Volto 4 alpha 18
So https://github.com/plone/training/commit/73b91ad0c52adb07c6e441a712530f4997d3ba36 needs to be checked for Volto 4 final.
> Volto hands on: Missing import and changed arguments of openObjectBrowser

- gatsby/gatsbysourceplone.rst
I just released gatsby-source-plone 0.2.0 where logLevel option has been removed, because we replaced custom logger with gatsby reporter API https://www.gatsbyjs.org/docs/node-api-helpers/#reporter
> Remove mention of removed logLevel option

- mastering-plone-5/zpt.rst
repeat.item.odd is a method in python expressions, so we should call it.
> Fix method call in ZPT exercises

- docs/mastering-plone/installation.md
@sneridagh, @tiberiuichim:  Problem: current Volto generator is 4.something which does not support NodeJS 16.
```
% yarn 
yarn install
Validating package.json...
error my-volto-project@1.0.0: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || ^14". Got "16.13.0"
error Found incompatible module.
```
> MPD: Update installation instructions for Plone 6 frontend

- .github/workflows/build_deploy.yml
- Makefile
I propose to temporarily disable the linkcheck for deployment.
https://github.com/plone/training/issues/574
> temporary exclude linkcheck

- docs/volto/bootstrap.md
```
$ yarn start
yarn run v1.22.15
error volto-starter-kit@8.4.0: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || ^14". Got "16.13.0"
error Commands cannot run with an incompatible environment.
```
> node 16 is unsupported

- .github/workflows/build_deploy.yml
- Makefile
- docs/mastering-plone/upgrade_steps.md
- docs/voltohandson/requirements.md
See #574.
This PR implements a more clear way to run the spellcheck and linkcheck tests in different steps, and indicates that linkcheck is temporarily disabled for build and deploy only.
It also fixes a couple of broken links and fixes a duplicate `.PHONY test` target.
> Separate test jobs in GitHub Actions

- docs/react/actions.md
- docs/react/callbacks.md
- docs/react/forms.md
- docs/react/initial_form_data.md
- docs/react/state.md
- docs/react/useeffect_hook.md
Closes #423 
The PR resolves issue #423 by adding a key prop in chapters 8, 10, 11, 12, 15, and 17 of the react training. Furthermore, it updates the `differences` section of each of these chapters so that there is no confusion whatsoever.
> React Training | Fixed: unique key prop warning

- Makefile
- docs/contributing/setup-build.md
- docs/wsgi/uwsgi.md
This PR makes it no longer required to activate the virtual environment by changing `make build` to `make bin/python`. It also updates the Contributing documentation. Finally this is now aligned with the main Plone 6 Documentation Makefile.
> No longer require virtual environment activation

- Makefile
- docs/glossary.md
- docs/mastering-plone-5/api.md
- docs/mastering-plone/api.md
- docs/testing/continuous_integration.md
- docs/voltohandson/header.md
- Use linkcheckbroken instead of linkcheck for a concise output.
See https://github.com/plone/training/pull/626#issuecomment-1179532828
> Use linkcheckbroken

- docs/mastering-plone/volto_custom_addon2.md
The example code for the faq block type was outdated. Those are the same fixes as in https://github.com/rohberg/volto-accordion-block/issues/1
> Update FAQ block type code example

- docs/voltohandson/eventlistingtemplate.md
Issue on page /voltohandson/eventlistingtemplate.html #682
> Variables name fix

- CHANGES.rst
- docs/plone-deployment/deploy.md
- docs/plone-deployment/new-project.md
- Add comment reminding user to have the repository on GitHub, so Docker images can be automatically generated.
- Add note about a `make` command needed due to a Volto generator unexpected behavior.
- Add comment about how to visit site once deployed locally.
> Minor edit to Plone Deployment sections

- docs/mastering-plone/features.md
Fixed a typo in 9.8. Default content types > Link where 'oder' was written instead of `or`
> Fixed a typo in 9.8. Default content types > Link

- docs/mastering-plone/configuring_customizing.md
In page:
[Mastering Plone 6 Development > 11. Configuring and Customizing Plone "Through The Web" > 11.1. The Control Panel > 11.1.1. General](https://training.plone.org/mastering-plone/configuring_customizing.html#general)
In the control panels list, changed the repeating **Mail** to **Url Management**
> Changed reapeating Mail to Url Management in 11.1.1 General, Control panels list

- docs/mastering-plone/volto_talkview.md
Removed unnecessary anchor tag <a href={`mailto:${content.email}`}> on the page [Mastering Plone 6 development > 22. Volto View Component: A Default View for a "Talk"](https://training.plone.org/mastering-plone/volto_talkview.html)  in the block where speaker email is added.
> Removed unnecessary anchor tag in code block in volto_talkview.md...#718

- docs/voltohandson/requirements.md
At [Project requirements](https://training.plone.org/voltohandson/requirements.html#project-requirements) there is a typo. It is written "includong" it should have been "including"
Closes #724
> Fixed the typo

- docs/mastering-plone-5/behaviors_2.md
- docs/mastering-plone-5/deployment_sites.md
- docs/mastering-plone-5/intro.md
- docs/mastering-plone-5/resources.md
- docs/mastering-plone/theming.md
- docs/ttw/workflow.md
- docs/wsgi/setup.md
Do not merge until the URL https://2022.training.plone.org/ is ready to deploy.
Although I have set this to "draft", it may be reviewed.
Refs:
- https://github.com/plone/training/issues/740
- https://github.com/plone/training/issues/672
> Update links in preparation for 2022 archive

- docs/conf.py
Currently https://training.plone.org/sitemap.xml contains entries for URLs such as: `<loc>https://training.plone.orgcontributing/authors.html</loc>`. Adding a trailing slash to the `html_baseurl` fixes this.
> Fix the content of sitemap.xml to use proper URLs.

- docs/theming/theme_diazo.md
I'm going trough the `Plone 6 Classic UI Theming` and found this minor glitch 😄 
A general question though: which source is _leading_ regarding Classic UI theming? training.plone.org or docs.plone.org? 🤔 
Given that on the last Plone Conference this train was not given, I'm not sure what's more recent/maintained.
Thanks for all the work, I've gone through all points until here and I can only say that it's impressive the work on `plonecli`, `bobtemplates.plone`, `mrbob` and of course all the great work on Plone 6 🎉 🥳 🤩
> Fix mentioned filename extension

- docs/mastering-plone/features.md
I, Vivek Kumar, agree to have this contribution published under the Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.
> Spelling Error inside the training docs

- Makefile
Issue Description:
The Makefile uses realpath to set SPHINXBUILD and SPHINXAUTOBUILD:
```
SPHINXBUILD     = $(realpath bin/sphinx-build)
SPHINXAUTOBUILD = $(realpath bin/sphinx-autobuild)
```
This can cause compatibility issues and doesn't handle special characters in paths. We need to replace realpath with a more portable and robust method. This issues was already discussed with @stevepiercy on plone community [conversation link](https://community.plone.org/t/error-running-training-repo-seek-advice-on-pull-request/18618/8?u=vivek-04022001)
I, Vivek Kumar, agree to have this contribution published under Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.
I humbly request the merging of this pull request as my Plone Contributor Agreement is …
> Enhance Path Handling in Makefile

- docs/voltohandson/quickstart.md
**I'm reading the Volto Hands-On documentation, and I've encountered some mistakes. I've raised a pull request to correct the errors.**
I, Vivek Kumar, agree to have this contribution published under the Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.
> Correct spelling errors and include omitted words in the documentation.

- docs/effective-volto/getting-started/project.md
Dead links for Plone Documentation. Updated with the ones from the [cookie-cutter-plone-starter](https://github.com/collective/cookiecutter-plone-starter?tab=readme-ov-file).
> Fix Broken Links

- docs/mastering-plone/volto_frontpage.md
In the chapter plural of "criterion" is written as both "criteria" (correct, more common) and "criterions" (less common and possibly incorrect). In either case, using two different ways to express the same meaning makes it confusing.
> Fix irregular plural noun

- docs/mastering-plone/dexterity.md
- docs/mastering-plone/relations.md
Fixes #843 issue.
Fixed typos.
I, Faakhir30, agree to have this contribution published under Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.
> Fix typos in documentation

- Makefile
`--clear` is the recommended way to wipe and recreate a clean Python virtual environment. `python3 -m venv venv --clear` will purge files and directories, such as `.git` and `.my_special_config`, from the current directory. This would be Very Bad™.
- Enhance `make distclean` such that it cleans both the docs _build directory and the virtual environment, then recreates the virtual environment and installs requirements into it. This is useful when your project gets confused about what exactly is in your virtual environment.
- Update internal Makefile command. No change to user commands.
Credit to @mrtango
----
📚 Documentation preview 📚: https://plone6--864.org.readthedocs.build/
> Move Python virtual environment into venv from root

- docs/index.md
- docs/volto-light-theme/adding-installing-new-block.md
- docs/volto-light-theme/creating-new-project.md
- docs/volto-light-theme/index.md
- docs/volto-light-theme/installing-vlt.md
- docs/volto-light-theme/question-answer.md
- docs/volto-light-theme/theming.md
----
📚 Documentation preview 📚: https://plone6--861.org.readthedocs.build/
> WIP! Volto Light Theme Training docs.

- docs/conf.py
- docs/customizing-volto-light-theme/installing-vlt.md
- docs/index.md
- Add VLT to the list of trainings displayed in the page
- Fix heading level in installing-vlt.md
- Make right side page contents menu expand to a minimum of 2 levels, if present, from the default of 1 level
- Add social icons
- Add extra footer
- Enable navigation with keys
@danalvrz @sneridagh also please watch for a PR for Volto to add the trainings to its docs.
----
📚 Documentation preview 📚: https://plone-training--884.org.readthedocs.build/
> VLT Training and page contents fixes

- docs/customizing-volto-light-theme/installing-vlt.md
alpha.1 doesn't work correctly when adding the Image block.
----
📚 Documentation preview 📚: https://plone-training--889.org.readthedocs.build/
> change vlt version from alpha.1 to alpha.2

- docs/plone-deployment/deploy.md
- docs/plone-deployment/index.md
- docs/plone-deployment/project-new.md
- docs/plone-deployment/troubleshoot.md
Closes #808.
Closes #759.
----
📚 Documentation preview 📚: https://plone-training--892.org.readthedocs.build/
> Deployment troubleshooting

- docs/documentation/index.md
- docs/index.md
See https://github.com/plone/documentation/pull/1801
----
📚 Documentation preview 📚: https://plone-training--894.org.readthedocs.build/
> Add a cross-reference to Plone 6 Documentation to the primary navigation

- docs/plone-deployment/deploy.md
There is no hint for self students how to interpret the interactive output options of `make test` or how to detect missing results.
Also the switching of the context in terminal is not explicitly mentioned. So I suggest two more lines how to switch back and forth. The context can be guessed by the path of the makefile, but this can be overseen.
Remark: This is also my first test for the Quick & Dirty `Suggest Edit` workflow from the docs UI.
> Update deploy - add more explicit details to invoke and use `make test` command.md

- docs/mastering-plone/installation.md
Reference for installation prerequisites is https://6.docs.plone.org/install/create-project-cookieplone.html#prerequisites-for-installation
----
📚 Documentation preview 📚: https://plone-training--926.org.readthedocs.build/
> Update reference installation prerequisites

- docs/teaching/index.md
Teaching implies a in my opinion outdated understanding of top down education. Some think they cannot teach. Some hate teachers. The actual content of that pages reflect a more modern  aproach and are more inviting. This should be also present in the wording of the TOC and Headlines.
The content can also be improved to a more encouraging onboarding of trainers beyond it is already trying this.
----
📚 Documentation preview 📚: https://plone-training--934.org.readthedocs.build/
> Update index.md change term Teaching to Giving a Training

- docs/voltohandson/plonereleasetype.md
Corrected the component spelling while exporting it . 
Component was PloneReleaseView , and while exporting it was written as PlonereleaseView.
I simply corrected the spelling in the export default line.
To save user's time from debugging small errors .
----
📚 Documentation preview 📚: https://plone-training--936.org.readthedocs.build/
> Corrected the component's spelling while exporting it in plonereleasetype.md file

- docs/voltoaddons/01-addon-basics.md
To load an add-on, the project needs to specify the add-on in the addons key of package.json of main project.
In the training  it was written project.json, I corrected it to package.json.
----
📚 Documentation preview 📚: https://plone-training--939.org.readthedocs.build/
> Addon is specified in package.json, not in project.json
